import React from 'react';

const Disclaimer = () => {
  return (
    <div className="analytics-container fade-in">
      <div className="section-header">
        <h2>⚠️ Medical Disclaimer</h2>
      </div>
      <div className="settings-card">
        <p className="description-text" style={{ fontSize: '1rem', lineHeight: '1.6' }}>
          <strong>IMPORTANT: </strong> The NeuroSSL platform and its associated deep learning models are provided for <strong>research, educational, and informational purposes only</strong>.
        </p>
        <p className="description-text" style={{ fontSize: '1rem', lineHeight: '1.6' }}>
          🏥 <strong>Not Medical Advice:</strong> The information generated by this tool should not be interpreted as a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
        </p>
        <p className="description-text" style={{ fontSize: '1rem', lineHeight: '1.6' }}>
          🔬 <strong>Experimental Status:</strong> The neural networks used in this application are experimental. While they employ advanced techniques such as Platt scaling and Monte Carlo dropout for uncertainty estimation, they can and will make mistakes.
        </p>
        <p className="description-text" style={{ fontSize: '1rem', lineHeight: '1.6' }}>
          👨‍⚕️ <strong>Clinician Verification Required:</strong> Any diagnostic reports or predictive outputs must be verified by a board-certified radiologist or appropriate medical professional before being considered in any clinical decision-making process.
        </p>
      </div>
    </div>
  );
};

export default Disclaimer;
